### ISSUE TITLE
finish/success

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/haptic#1]
It would be good to have some form of feedback/reward to indicate the user has finished/won the game. While they will realize they are done when their finger leaves the screen, they don't know when they have left the actual browser window. If they haven't just finished but even won, they deserve a reward :-) A little tune or special vibration pattern?

**Comment by DorisAtCeR** [comment]
1) Can the tune be a bit more gentle/subtle? 
2) Is there a difference between reaching the top without having touched the black borders (I did not succeed in doing so this time) and reaching the top after navigating the path while hitting the borders sometimes?
3) It might be nice to have either sound only when the user has actually attempted to do the game rather than to just tap into the top green zone.

**Comment by neon-ninja** [comment]
1. Do you have a specific tune in mind? Would you be able to provide an mp3/wav sound clip?
2. No - I think the game would be too hard then. I'm allowing the user to cheat currently, if they so desire.
3. What would the requirement be logically then? Touch the bottom green zone then the top zone, without lifting your finger?

**Comment by DorisAtCeR** [comment]
3. Maybe they have moved their finger over every row even if not along the entire length of the row? Again, it depends on the purpose and goal of the game.
