### ISSUE TITLE
UX: Top and bottom bar

### ISSUE THREAD

**Issue by DorisAtCeR** [UoA-eResearch/haptic#4]
It would be nice if the users could have different vibration patterns for touching the top and bottom bar. That would help them in their orientation.

**Comment by DorisAtCeR** [comment]
Did you do this? If so, neither me nor Noel can feel the different pattern, strength of signal or whatever you might have varied.

**Comment by neon-ninja** [comment]
Yes - the old version may be cached? Try https://rawgit.com/UoA-eResearch/haptic/v1.0/ to be certain you're on that version

**Comment by DorisAtCeR** [comment]
I meant top of the black or bottom of the black lines. Not the green areas. But all good. For futher changes maybe first find out what David has envisaged in detail.
